baseurl = "https://mostafaeissa.github.io"
title = "Beyond Lambda"
languageCode = "en-us"
paginate = 10
paginatePath = "page"
theme = "humin"
mathjax = true
mathjaxEnableSingleDollar = true

[params]
description = ""
keywords = []
author = "Mostafa Abdelrahman"
profilePicture = "/android-chrome-512x512.png"

[taxonomies]
tag = "tags"
topic = "topics"
	

[[params.static_pages]]
url = "/about/"
tag = "about"

[[params.social]]
url = "https://github.com/MostafaEissa"
fa_icon = "fa-github"

[[params.social]]
url = "https://linkedin.com/in/mostafa-abdelrahman-16356b12a"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"


